// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication10.DataAccess.Base;

namespace WebApplication10.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("WebApplication10.Models.Order_data", b =>
                {
                    b.Property<string>("order_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("buyer_id");

                    b.Property<string>("car_id");

                    b.Property<DateTime>("date_order");

                    b.Property<int>("price_buyer");

                    b.Property<int>("price_seller");

                    b.Property<string>("seller_id");

                    b.Property<string>("status");

                    b.HasKey("order_id");

                    b.ToTable("order_data");
                });

            modelBuilder.Entity("WebApplication10.Models.person", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("name")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("person");
                });

#pragma warning restore 612, 618
        }
    }
}
